// ========================================================================
// LinkageConditionNode.qml — 联动规则条件树节点编辑器 (P1 #5)
// 独立文件以支持递归自引用 (内联 component 不允许自递归)
// 数据模型: { node_type: "AND"|"OR"|"LEAF", leaf_type, field, op, value, children: [...] }
// 支持 AND/OR 嵌套 (深度 ≤ 3); LEAF 节点是叶子
// ========================================================================
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Column {
    id: cne
    property var node: ({ node_type: "LEAF", field: "event_type", op: "==", value: "" })
    property int depth: 0
    // nodeChanged signal auto-generated by `property var node`

    function refresh(n) {
        // 强制刷新: 重新赋值 node
        node = JSON.parse(JSON.stringify(n))
    }
    function deleteChild(idx) {
        if (Array.isArray(node.children)) {
            node.children.splice(idx, 1)
            nodeChanged()
        }
    }
    function addChild() {
        if (!Array.isArray(node.children)) node.children = []
        node.children.push({ node_type: "LEAF", leaf_type: "SOURCE", field: "event_type", op: "==", value: "" })
        nodeChanged()
    }
    function addOrChild() {
        if (!Array.isArray(node.children)) node.children = []
        node.children.push({ node_type: "OR", children: [{ node_type: "LEAF", leaf_type: "SOURCE", field: "event_type", op: "==", value: "" }] })
        nodeChanged()
    }
    function promoteType(t) {
        node.node_type = t
        if ((t === "AND" || t === "OR") && !Array.isArray(node.children)) node.children = []
        nodeChanged()
    }

    // 节点背景色按类型
    Rectangle {
        width: parent ? parent.width : 0
        height: cneColumn.implicitHeight + 8
        color: cne.node.node_type === "AND" ? "#1A2A3A" : cne.node.node_type === "OR" ? "#2A1A3A" : "#1A1D23"
        radius: 4
        border.color: cne.depth === 0 ? "#FFB800" : (cne.node.node_type === "AND" ? "#3B82F6" : cne.node.node_type === "OR" ? "#6C5CE7" : "#252830")
        border.width: 1

        Column {
            id: cneColumn
            anchors.fill: parent; anchors.margins: 4; spacing: 4

            // 头: 类型选择 + 操作
            Row { spacing: 6; width: parent.width
                Rectangle { width: 8; height: 18; radius: 2; color: cne.depth === 0 ? "#FFB800" : "#3B82F6" }
                ComboBox {
                    id: typeCombo
                    width: 80; height: 22
                    model: cne.depth === 0 ? ["AND", "OR"] : ["AND", "OR", "LEAF"]
                    currentIndex: Math.max(0, model.indexOf(cne.node.node_type || "LEAF"))
                    onActivated: cne.promoteType(model[currentIndex])
                    background: Rectangle { color: "#252830"; radius: 3 }
                    contentItem: Text { text: parent.displayText; font.pixelSize: 12; color: "#E8E8E8"; leftPadding: 4; verticalAlignment: Text.AlignVCenter }
                }
                Text { text: cne.node.node_type === "LEAF" ? "叶子节点 (depth=" + cne.depth + ")" : "组合节点 (depth=" + cne.depth + ", children=" + (cne.node.children ? cne.node.children.length : 0) + ")"; font.pixelSize: 12; color: "#8B8FA3"; anchors.verticalCenter: parent.verticalCenter }
                Item { Layout.fillWidth: true }
            }

            // LEAF 节点: field/op/value 编辑器
            Column {
                visible: cne.node.node_type === "LEAF"
                width: parent.width
                spacing: 4
                Row { spacing: 4
                    Text { text: "字段:"; font.pixelSize: 12; color: "#8B8FA3"; anchors.verticalCenter: parent.verticalCenter; width: 32 }
                    ComboBox {
                        id: fieldCombo; width: 130; height: 24
                        model: ["event_type", "channel_id", "min_severity", "min_confidence", "region_id", "location_id", "device_group_id", "time"]
                        currentIndex: Math.max(0, model.indexOf(cne.node.field || ""))
                        onActivated: { cne.node.field = model[currentIndex]; cne.nodeChanged() }
                        background: Rectangle { color: "#252830"; radius: 3 }
                        contentItem: Text { text: parent.displayText; font.pixelSize: 12; color: "#E8E8E8"; leftPadding: 4; verticalAlignment: Text.AlignVCenter }
                    }
                    Text { text: "运算:"; font.pixelSize: 12; color: "#8B8FA3"; anchors.verticalCenter: parent.verticalCenter; width: 32 }
                    ComboBox {
                        id: opCombo; width: 70; height: 24
                        model: ["==", "!=", ">=", "<=", "in", "between"]
                        currentIndex: Math.max(0, model.indexOf(cne.node.op || "=="))
                        onActivated: { cne.node.op = model[currentIndex]; cne.nodeChanged() }
                        background: Rectangle { color: "#252830"; radius: 3 }
                        contentItem: Text { text: parent.displayText; font.pixelSize: 12; color: "#E8E8E8"; leftPadding: 4; verticalAlignment: Text.AlignVCenter }
                    }
                    Text { text: "值:"; font.pixelSize: 12; color: "#8B8FA3"; anchors.verticalCenter: parent.verticalCenter; width: 24 }
                    TextField {
                        id: valueField; width: 130; height: 24
                        text: cne.node.value !== undefined ? cne.node.value.toString() : ""
                        color: "#E8E8E8"; font.pixelSize: 12
                        background: Rectangle { color: "#252830"; radius: 3 }
                        onTextChanged: {
                            var v = text
                            if (cne.node.field === "min_severity") v = parseInt(text) || 0
                            else if (cne.node.field === "min_confidence") v = parseFloat(text) || 0
                            cne.node.value = v
                            cne.nodeChanged()
                        }
                    }
                }
            }

            // AND/OR 节点: children 递归编辑器
            Column {
                visible: cne.node.node_type === "AND" || cne.node.node_type === "OR"
                width: parent.width
                spacing: 4
                Repeater {
                    model: cne.node.children || []
                    delegate: Item {
                        width: parent.width
                        height: childLoader.item ? childLoader.item.implicitHeight + 4 : 4
                        property int childIndex: index
                        // 用 Loader 延迟加载打破 Qt6 编译期递归检测
                        Loader {
                            id: childLoader
                            anchors.left: parent.left; anchors.right: deleteBtn.left; anchors.rightMargin: 4
                            source: "qrc:/LinkageConditionNode.qml"
                            onLoaded: {
                                item.node = modelData
                                item.depth = cne.depth + 1
                                item.nodeChanged.connect(function() { cne.nodeChanged() })
                            }
                        }
                        Button {
                            id: deleteBtn
                            anchors.right: parent.right; anchors.top: parent.top
                            width: 24; height: 24
                            text: "X"; font.pixelSize: 12
                            background: Rectangle { color: "transparent" }
                            contentItem: Text { text: parent.text; font.pixelSize: 12; color: "#FF3D71" }
                            onClicked: cne.deleteChild(parent.parent.childIndex)
                        }
                    }
                }
                Row { spacing: 4
                    Button { text: "+ LEAF"; font.pixelSize: 12
                        onClicked: cne.addChild()
                        background: Rectangle { color: "#3B82F6"; radius: 3; width: 60; height: 22 }
                        contentItem: Text { text: parent.text; font.pixelSize: 12; color: "#FFF"; horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter } }
                    Button { text: "+ 嵌入 OR 子组"; font.pixelSize: 12
                        enabled: cne.depth < 2
                        onClicked: cne.addOrChild()
                        background: Rectangle { color: enabled ? "#6C5CE7" : "#252830"; radius: 3; width: 90; height: 22 }
                        contentItem: Text { text: parent.text; font.pixelSize: 12; color: enabled ? "#FFF" : "#8B8FA3"; horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter } }
                }
            }
        }
    }
}